name: Generate and Deploy DBT Docs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-and-deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create DBT profiles
      run: |
        mkdir -p ~/.dbt
        cat > ~/.dbt/profiles.yml << 'EOF'
        dbt_poc:
          outputs:
            prod:
              type: postgres
              host: ${{ secrets.DBT_HOST }}
              port: 5432
              user: ${{ secrets.DBT_USER }}
              pass: ${{ secrets.DBT_PASSWORD }}
              dbname: ${{ secrets.DBT_DBNAME }}
              schema: dbt
              threads: 4
          target: prod
        EOF

    - name: Run DBT Debug
      run: |
        cd dbt_poc
        dbt debug
    
    - name: Generate DBT docs
      run: |
        cd dbt_poc
        dbt deps
        dbt docs generate
        
    - name: Copy docs to docs directory
      run: |
        rm -rf docs/*
        ls -la dbt_poc/target/
        cp -f dbt_poc/target/catalog.json docs/
        cp -f dbt_poc/target/manifest.json docs/
        cp -f dbt_poc/target/graph.gpickle docs/
        cp -f dbt_poc/target/index.html docs/
        
    - name: Commit and push if changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs/
        git commit -m "Auto-update DBT documentation" || echo "No changes to commit"
        git push

  trigger-cloudflare-deploy:
    needs: generate-and-deploy-docs
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cloudflare Pages deployment
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"